all: 
	gcc -Wall -pedantic -c lab6.c
	gcc -Wall -pedantic -c re.c 
	gcc -o lab6 lab6.o re.o

clang:
	clang -Wall -pedantic -c lab6.c
	clang -Wall -pedantic -c re.c 
	clang -o lab6 lab6.o re.o

clean:
	rm -f lab6.o re.o lab6
